[project]
name = 'WitStacContract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = [{contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"}]
[contracts.wit-token]
path = 'contracts/wit-token.clar'
clarity_version = 2
epoch = '2.5'

[contracts.witstac]
path = 'contracts/witstac.clar'
clarity_version = 2
epoch = '2.5'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
